### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by UnrulyNatives** [TimothyDJones/awesome-laravel#2]
Hi, a small suggestion.
You should include dates so that we could keep track of new packages without browsking commits.

Great list, by the way. Thanks!

**Comment by TimothyDJones** [comment]
Thanks, Peter, for the suggestion!  I realized the other day that as the list grows, it's getting harder to know the context.  I'll start adding dates when I make updates.     From: Peter <notifications@github.com>
 To: TimothyDJones/awesome-laravel <awesome-laravel@noreply.github.com> 
 Sent: Saturday, April 4, 2015 3:59 AM
 Subject: [awesome-laravel] 2 suggestions (#2)
   
Hi, a small suggestion.
You should include dates so that we could keep track of new packages without browsking commits.Great list, by the way. Thanks!—

**Comment by TimothyDJones** [comment]
Started including date at end of each item when added.
